[package]
name = "test4"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
reedline = "0.37.0"
serde = "1.0.216"
serde_json = "1.0" 
chrono = "0.4"
rustyline = "15.0" 
ipnetwork = "0.20.0"
lazy_static = "1.4"